In [184]:
import pandas as pd

In [185]:
df=pd.read_csv("telecom_churn_data_full.csv")
print(df.shape)

(243553, 14)

In [186]:
df.head()

,customer_id,telecom_partner,gender,age,state,city,pincode,date_of_registration,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn
0,1,Reliance Jio,F,25,Karnataka,Kolkata,755597,2020-01-01,4,124962,44,45,-361,0
1,2,Reliance Jio,F,55,Mizoram,Mumbai,125926,2020-01-01,2,130556,62,39,5973,0
2,3,Vodafone,F,57,Arunachal Pradesh,Delhi,423976,2020-01-01,0,148828,49,24,193,1
3,4,BSNL,M,46,Tamil Nadu,Kolkata,522841,2020-01-01,1,38722,80,25,9377,1
4,5,BSNL,F,26,Tripura,Delhi,740247,2020-01-01,2,55098,78,15,1393,0

In [187]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243553 entries, 0 to 243552
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   customer_id           243553 non-null  int64
 1   telecom_partner       243553 non-null  object
 2   gender                243553 non-null  object
 3   age                   243553 non-null  int64
 4   state                 243553 non-null  object
 5   city                  243553 non-null  object
 6   pincode               243553 non-null  int64
 7   date_of_registration  243553 non-null  object
 8   num_dependents        243553 non-null  int64
 9   estimated_salary      243553 non-null  int64
 10  calls_made            243553 non-null  int64
 11  sms_sent              243553 non-null  int64
 12  data_used             243553 non-null  int64
 13  churn                 243553 non-null  int64
dtypes: int64(9), object(5)
memory usage: 26.0+ MB

In [188]:
df.isnull().sum()

customer_id             0
telecom_partner         0
gender                  0
age                     0
state                   0
city                    0
pincode                 0
date_of_registration    0
num_dependents          0
estimated_salary        0
calls_made              0
sms_sent                0
data_used               0
churn                   0
dtype: int64

In [189]:
df.columns

Index(['customer_id', 'telecom_partner', 'gender', 'age', 'state', 'city',
       'pincode', 'date_of_registration', 'num_dependents', 'estimated_salary',
       'calls_made', 'sms_sent', 'data_used', 'churn'],
      dtype='object')

In [190]:
df['churn'].value_counts()

churn
0    194726
1     48827
Name: count, dtype: int64

In [191]:
(df['churn'].value_counts(normalize=True)*100).round(2)

churn
0    79.95
1    20.05
Name: proportion, dtype: float64

In [192]:
df.dtypes

customer_id              int64
telecom_partner         object
gender                  object
age                      int64
state                   object
city                    object
pincode                  int64
date_of_registration    object
num_dependents           int64
estimated_salary         int64
calls_made               int64
sms_sent                 int64
data_used                int64
churn                    int64
dtype: object

In [193]:
df.describe()

,customer_id,age,pincode,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn
count,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000
mean,121777.000000,46.077609,549501.270541,1.997500,85021.137839,49.010548,23.945404,4993.186025,0.200478
std,70307.839393,16.444029,259808.860574,1.414941,37508.963233,29.453556,14.733575,2942.019547,0.400359
min,1.000000,18.000000,100006.000000,0.000000,20000.000000,-10.000000,-5.000000,-987.000000,0.000000
25%,60889.000000,32.000000,324586.000000,1.000000,52585.000000,24.000000,11.000000,2490.000000,0.000000
50%,121777.000000,46.000000,548112.000000,2.000000,84990.000000,49.000000,24.000000,4987.000000,0.000000
75%,182665.000000,60.000000,774994.000000,3.000000,117488.000000,74.000000,36.000000,7493.000000,0.000000
max,243553.000000,74.000000,999987.000000,4.000000,149999.000000,108.000000,53.000000,10991.000000,1.000000

In [194]:
(df['calls_made'] < 0).sum()

np.int64(6713)

In [195]:
(df['sms_sent'] < 0).sum()

np.int64(7375)

In [196]:
(df['data_used'] < 0).sum()

np.int64(6050)

In [197]:
df['calls_made'] = df['calls_made'].clip(lower=0)
df['sms_sent'] = df['sms_sent'].clip(lower=0)
df['data_used'] = df['data_used'].clip(lower=0)

In [198]:
(df['calls_made'] < 0).sum()

np.int64(0)

In [199]:
(df['sms_sent'] < 0).sum()

np.int64(0)

In [200]:
(df['sms_sent'] < 0).sum()

np.int64(0)

In [201]:
df.describe()

,customer_id,age,pincode,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn
count,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000
mean,121777.000000,46.077609,549501.270541,1.997500,85021.137839,49.120122,24.015754,5001.354802,0.200478
std,70307.839393,16.444029,259808.860574,1.414941,37508.963233,29.260198,14.611419,2927.420055,0.400359
min,1.000000,18.000000,100006.000000,0.000000,20000.000000,0.000000,0.000000,0.000000,0.000000
25%,60889.000000,32.000000,324586.000000,1.000000,52585.000000,24.000000,11.000000,2490.000000,0.000000
50%,121777.000000,46.000000,548112.000000,2.000000,84990.000000,49.000000,24.000000,4987.000000,0.000000
75%,182665.000000,60.000000,774994.000000,3.000000,117488.000000,74.000000,36.000000,7493.000000,0.000000
max,243553.000000,74.000000,999987.000000,4.000000,149999.000000,108.000000,53.000000,10991.000000,1.000000

In [202]:
df['gender'].value_counts()

gender
M    145977
F     97576
Name: count, dtype: int64

In [203]:
pd.crosstab(df['gender'], df['churn'])

churn        0      1
gender
F        77771  19805
M       116955  29022

In [204]:
df['age'].value_counts().sort_index()

age
18    4128
19    4314
20    4287
21    4259
22    4271
23    4299
24    4316
25    4152
26    4111
27    4229
28    4264
29    4329
30    4254
31    4211
32    4228
33    4265
34    4212
35    4199
36    4218
37    4391
38    4392
39    4256
40    4248
41    4153
42    4337
43    4187
44    4329
45    4138
46    4248
47    4264
48    4414
49    4283
50    4341
51    4423
52    4141
53    4312
54    4254
55    4325
56    4257
57    4190
58    4154
59    4262
60    4424
61    4331
62    4402
63    4378
64    4228
65    4327
66    4349
67    4313
68    4301
69    4278
70    4290
71    4317
72    4294
73    4297
74    4179
Name: count, dtype: int64

In [205]:
df['age_group'] = pd.cut(
    df['age'],
    bins=[18,30,50,74],
    labels=['Young','Middle','Senior'],
    include_lowest=True)

In [206]:
df[['age','age_group']].head(10)

   age age_group
0   25     Young
1   55    Senior
2   57    Senior
3   46    Middle
4   26     Young
5   36    Middle
6   60    Senior
7   46    Middle
8   53    Senior
9   57    Senior

In [207]:
df['age_group'].value_counts()

age_group
Senior    103026
Middle     85314
Young      55213
Name: count, dtype: int64

In [208]:
pd.crosstab(df['age_group'],df['churn'])

churn          0      1
age_group
Young      44274  10939
Middle     68091  17223
Senior     82361  20665

In [209]:
df['telecom_partner'].value_counts()

telecom_partner
Reliance Jio    61123
Airtel          60905
Vodafone        60802
BSNL            60723
Name: count, dtype: int64

In [210]:
pd.crosstab(df['telecom_partner'],df['churn'])

churn                0      1
telecom_partner
Airtel           48501  12404
BSNL             48663  12060
Reliance Jio     48889  12234
Vodafone         48673  12129

In [211]:
(pd.crosstab(
    df['telecom_partner'],
    df['churn'],
    normalize='index'
) * 100).round(2)

churn                0      1
telecom_partner
Airtel           79.63  20.37
BSNL             80.14  19.86
Reliance Jio     79.98  20.02
Vodafone         80.05  19.95

In [212]:
df.groupby('churn')['calls_made'].mean()

churn
0    49.094178
1    49.223585
Name: calls_made, dtype: float64

In [213]:
df.groupby('churn')['data_used'].mean()

churn
0    5000.235757
1    5005.817642
Name: data_used, dtype: float64

In [214]:
df.groupby('churn')['estimated_salary'].mean()

churn
0    85083.726934
1    84771.527495
Name: estimated_salary, dtype: float64

In [215]:
df.groupby('churn')['num_dependents'].mean()

churn
0    1.999302
1    1.990313
Name: num_dependents, dtype: float64

In [216]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243553 entries, 0 to 243552
Data columns (total 15 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   customer_id           243553 non-null  int64
 1   telecom_partner       243553 non-null  object
 2   gender                243553 non-null  object
 3   age                   243553 non-null  int64
 4   state                 243553 non-null  object
 5   city                  243553 non-null  object
 6   pincode               243553 non-null  int64
 7   date_of_registration  243553 non-null  object
 8   num_dependents        243553 non-null  int64
 9   estimated_salary      243553 non-null  int64
 10  calls_made            243553 non-null  int64
 11  sms_sent              243553 non-null  int64
 12  data_used             243553 non-null  int64
 13  churn                 243553 non-null  int64
 14  age_group             243553 non-null  category
dtypes: category(1), int64(9), object(5)
memory usage: 26.2+ MB

In [217]:
df['date_of_registration'].head()

0    2020-01-01
1    2020-01-01
2    2020-01-01
3    2020-01-01
4    2020-01-01
Name: date_of_registration, dtype: object

In [218]:
df['date_of_registration'].nunique()

1220

In [219]:
df['date_of_registration'] = pd.to_datetime(df['date_of_registration'])

In [220]:
df['date_of_registration'].dtype

dtype('<M8[ns]')

In [221]:
df['date_of_registration'].min()

Timestamp('2020-01-01 00:00:00')

In [222]:
df['date_of_registration'].max()

Timestamp('2023-05-04 00:00:00')

In [223]:
reference_date = df['date_of_registration'].max()

df['tenure_days'] = (
    reference_date - df['date_of_registration']
).dt.days

In [224]:
df[['date_of_registration','tenure_days']].head()

  date_of_registration  tenure_days
0           2020-01-01         1219
1           2020-01-01         1219
2           2020-01-01         1219
3           2020-01-01         1219
4           2020-01-01         1219

In [225]:
df.groupby('churn')['tenure_days'].mean()

churn
0    610.290875
1    608.839945
Name: tenure_days, dtype: float64

In [226]:
df[['age','num_dependents','estimated_salary',
    'calls_made','sms_sent','data_used',
    'tenure_days','churn']].corr()

,age,num_dependents,estimated_salary,calls_made,sms_sent,data_used,tenure_days,churn
age,1.000000,0.001462,-0.003103,-0.001369,-0.002828,0.000773,0.001101,0.000839
num_dependents,0.001462,1.000000,0.002157,0.000286,0.002144,0.003093,0.000464,-0.002543
estimated_salary,-0.003103,0.002157,1.000000,-0.000138,0.002565,-0.003339,-0.000193,-0.003332
calls_made,-0.001369,0.000286,-0.000138,1.000000,0.000127,0.001168,-0.003455,0.001771
sms_sent,-0.002828,0.002144,0.002565,0.000127,1.000000,-0.002898,-0.000180,-0.003086
data_used,0.000773,0.003093,-0.003339,0.001168,-0.002898,1.000000,-0.000649,0.000763
tenure_days,0.001101,0.000464,-0.000193,-0.003455,-0.000180,-0.000649,1.000000,-0.001651
churn,0.000839,-0.002543,-0.003332,0.001771,-0.003086,0.000763,-0.001651,1.000000

In [227]:
df.drop(['customer_id','pincode'], axis=1)

,telecom_partner,gender,age,state,city,date_of_registration,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn,age_group,tenure_days
0,Reliance Jio,F,25,Karnataka,Kolkata,2020-01-01,4,124962,44,45,0,0,Young,1219
1,Reliance Jio,F,55,Mizoram,Mumbai,2020-01-01,2,130556,62,39,5973,0,Senior,1219
2,Vodafone,F,57,Arunachal Pradesh,Delhi,2020-01-01,0,148828,49,24,193,1,Senior,1219
3,BSNL,M,46,Tamil Nadu,Kolkata,2020-01-01,1,38722,80,25,9377,1,Middle,1219
4,BSNL,F,26,Tripura,Delhi,2020-01-01,2,55098,78,15,1393,0,Young,1219
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243548,Airtel,F,28,Mizoram,Kolkata,2023-05-03,3,130580,28,9,4102,0,Young,1
243549,Reliance Jio,F,52,Assam,Kolkata,2023-05-03,0,82393,80,45,7521,0,Senior,1
243550,Reliance Jio,M,59,Tripura,Kolkata,2023-05-03,4,51298,26,4,6547,0,Senior,1
243551,BSNL,M,49,Madhya Pradesh,Kolkata,2023-05-03,2,83981,80,15,1125,0,Middle,1
243552,BSNL,F,37,Telangana,Hyderabad,2023-05-04,0,144297,61,7,3384,0,Middle,0

In [228]:
df.select_dtypes(include='object').columns

Index(['telecom_partner', 'gender', 'state', 'city'], dtype='object')

In [229]:
df['gender'] = df['gender'].map({'M':0,'F':1})

In [230]:
df['gender'].head()

0    1
1    1
2    1
3    0
4    1
Name: gender, dtype: int64

In [231]:
df.columns.tolist()

['customer_id',
 'telecom_partner',
 'gender',
 'age',
 'state',
 'city',
 'pincode',
 'date_of_registration',
 'num_dependents',
 'estimated_salary',
 'calls_made',
 'sms_sent',
 'data_used',
 'churn',
 'age_group',
 'tenure_days']

In [232]:
df.columns

Index(['customer_id', 'telecom_partner', 'gender', 'age', 'state', 'city',
       'pincode', 'date_of_registration', 'num_dependents', 'estimated_salary',
       'calls_made', 'sms_sent', 'data_used', 'churn', 'age_group',
       'tenure_days'],
      dtype='object')

In [233]:
df = df.drop(['customer_id','pincode'], axis=1)

In [234]:
df.columns

Index(['telecom_partner', 'gender', 'age', 'state', 'city',
       'date_of_registration', 'num_dependents', 'estimated_salary',
       'calls_made', 'sms_sent', 'data_used', 'churn', 'age_group',
       'tenure_days'],
      dtype='object')

In [235]:
df = df.drop('date_of_registration', axis=1)

In [236]:
df = pd.get_dummies(
    df,
    columns=['telecom_partner','state','city','age_group'],
    drop_first=True
)

In [237]:
df.shape

(243553, 46)

In [238]:
X = df.drop('churn', axis=1)
y = df['churn']

In [239]:
print(X.shape)
print(y.shape)

(243553, 45)
(243553,)

In [240]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [241]:
print(X_train.shape)
print(X_test.shape)

(194842, 45)
(48711, 45)

In [242]:
X.isnull().sum().sort_values(ascending=False).head(10)

gender               0
state_Maharashtra    0
state_Meghalaya      0
state_Mizoram        0
state_Nagaland       0
state_Odisha         0
state_Punjab         0
state_Rajasthan      0
state_Sikkim         0
state_Tamil Nadu     0
dtype: int64

In [243]:
df['gender'].value_counts(dropna=False)

gender
0    145977
1     97576
Name: count, dtype: int64

In [244]:
df_backup = pd.read_csv("telecom_churn_data_full.csv")

In [245]:
df_backup['gender'].value_counts()

gender
M    145977
F     97576
Name: count, dtype: int64

In [246]:
df['gender'] = df_backup['gender'].map({'M':0,'F':1})

In [247]:
df['gender'].value_counts(dropna=False)

gender
0    145977
1     97576
Name: count, dtype: int64

In [248]:
X = df.drop('churn', axis=1)

X.isnull().sum().sort_values(ascending=False).head(10)

gender               0
state_Maharashtra    0
state_Meghalaya      0
state_Mizoram        0
state_Nagaland       0
state_Odisha         0
state_Punjab         0
state_Rajasthan      0
state_Sikkim         0
state_Tamil Nadu     0
dtype: int64

In [249]:
X = df.drop('churn', axis=1)
y = df['churn']

In [250]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [251]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

In [252]:
model.fit(X_train, y_train)

C:\Users\SounderyaChandran\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [253]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.7991624068485558

In [254]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[38928,     0],
       [ 9783,     0]])

In [255]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89     38928
           1       0.00      0.00      0.00      9783

    accuracy                           0.80     48711
   macro avg       0.40      0.50      0.44     48711
weighted avg       0.64      0.80      0.71     48711

C:\Users\SounderyaChandran\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\SounderyaChandran\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\SounderyaChandran\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [256]:
from sklearn.ensemble import RandomForestClassifier

In [257]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

In [258]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [259]:
y_pred_rf = rf_model.predict(X_test)

In [260]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred_rf))

Accuracy: 0.7991418776046478

In [261]:
confusion_matrix(y_test, y_pred_rf)

array([[38927,     1],
       [ 9783,     0]])

In [262]:
from sklearn.linear_model import LogisticRegression

balanced_model = LogisticRegression(
    class_weight='balanced',
    max_iter=1000
)

balanced_model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [263]:
y_pred_balanced = balanced_model.predict(X_test)

In [264]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred_balanced))
print(classification_report(y_test, y_pred_balanced))

[[20016 18912]
 [ 4897  4886]]
              precision    recall  f1-score   support

           0       0.80      0.51      0.63     38928
           1       0.21      0.50      0.29      9783

    accuracy                           0.51     48711
   macro avg       0.50      0.51      0.46     48711
weighted avg       0.68      0.51      0.56     48711

In [265]:
churn_probability = balanced_model.predict_proba(X_test)[:,1]

In [266]:
results = pd.DataFrame({
    'Actual_Churn': y_test,
    'CHURN_FLAG': y_pred_balanced,
    'CHURN_RISK_SCORE': churn_probability
})

In [267]:
results.head()

        Actual_Churn  CHURN_FLAG  CHURN_RISK_SCORE
230796             0           0          0.487459
191985             0           1          0.501468
18778              0           0          0.487730
241016             0           0          0.494396
136494             0           0          0.497559

In [268]:
results['CHURN_FLAG'].value_counts()

CHURN_FLAG
0    24913
1    23798
Name: count, dtype: int64

In [269]:
results.to_csv('churn_predictions.csv', index=False)

In [270]:
X_test.shape

(48711, 45)

In [271]:
dashboard_data = X_test.copy()

dashboard_data['Actual_Churn'] = y_test.values
dashboard_data['CHURN_FLAG'] = y_pred_balanced
dashboard_data['CHURN_RISK_SCORE'] = churn_probability

dashboard_data.to_csv('telecom_churn_dashboard_data.csv', index=False)

In [274]:
pd.read_csv('telecom_churn_dashboard_data.csv').head()

,gender,age,num_dependents,estimated_salary,calls_made,sms_sent,data_used,tenure_days,telecom_partner_BSNL,telecom_partner_Reliance Jio,...,city_Chennai,city_Delhi,city_Hyderabad,city_Kolkata,city_Mumbai,age_group_Middle,age_group_Senior,Actual_Churn,CHURN_FLAG,CHURN_RISK_SCORE
0,0,20,2,104752,38,47,1687,64,False,False,...,False,True,False,False,False,False,False,0,0,0.487459
1,1,68,2,71706,43,33,991,259,False,False,...,False,True,False,False,False,False,True,0,1,0.501468
2,0,30,4,137473,0,12,6803,1126,False,False,...,False,False,False,False,True,False,False,0,0,0.487730
3,0,22,0,58245,32,11,2832,13,False,False,...,True,False,False,False,False,False,False,0,0,0.494396
4,0,63,4,73740,68,11,5375,536,False,True,...,False,False,False,False,False,False,True,0,0,0.497559